services:
  - type: web
    name: a2e-backend
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "node index.js"
    envVars:
      - key: PORT
        fromDatabase: false
        value: "10000" # Render provides a $PORT automatically; you can leave it empty
